#!/bin/bash
#
# [Quick Box :: Remove extsearch plugin]
#
# GitHub _ packages:   https://github.com/QuickBox/quickbox_packages
# GitHub _ plugins:    https://github.com/QuickBox/quickbox_rutorrent-plugins
# Author:   QuickBox.IO | JMSolo
# URL:      https://plaza.quickbox.io
#
# QuickBox Copyright (C) 2016 Swizards.net
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
OUTTO=/srv/rutorrent/home/db/output.log

function _removeplugin-extsearch() {
  username=$(whoami);
  rutorrent="/srv/rutorrent/";
  echo "Uninstalling the extsearch plugin ... " >>"${OUTTO}" 2>&1;
  PLUGIN="extsearch"
    for i in $PLUGIN; do
      rm -rf "${rutorrent}plugins/$i"
    done
  sleep 5

  echo "Extsearch Plugin Uninstall Complete!" >>"${OUTTO}" 2>&1;
  sleep 5

  echo "Refreshing your browser in 5 seconds" >>"${OUTTO}" 2>&1;
  sleep 5

  printf "" > /srv/rutorrent/home/db/output.log
  exit
}

_removeplugin-extsearch
