#!/bin/bash
#
# [Quick Network Interface Input]
#
# GitHub:   https://github.com/JMSDOnline/QuickBox
# Author:   Swizards.net
# URL:      https://swizards.net
#
# QuickBox Copyright (C) 2016 Swizards.net
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
function _string() { perl -le 'print map {(a..z,A..Z,0..9)[rand 62] } 0..pop' 15 ; }
Reth0=$(ifconfig | grep -m 1 "Link encap" | sed 's/[ \t].*//;/^\(lo\|\)$/d' | awk '{ print $1 '});
IFACE=$(echo -n "${Reth0}");
function _setinterface {

	sed -i "s/INETFACE/${IFACE}/g" /srv/rutorrent/home/widgets/stat.php;
	sed -i "s/INETFACE/${IFACE}/g" /srv/rutorrent/home/widgets/data.php;
	sed -i "s/INETFACE/${IFACE}/g" /srv/rutorrent/home/widgets/config.php;
	sed -i "s/INETFACE/${IFACE}/g" /srv/rutorrent/home/inc/config.php;

}
Reth0=$(ifconfig | grep -m 1 "Link encap" | sed 's/[ \t].*//;/^\(lo\|\)$/d' | awk '{ print $1 '});
IFACE=$(echo -n "${Reth0}");
_setinterface
