#!/bin/bash
#
# [Quick Box :: Install rpc plugin]
#
# GitHub _ packages:   https://github.com/QuickBox/quickbox_packages
# GitHub _ plugins:    https://github.com/QuickBox/quickbox_rutorrent-plugins
# Author:   QuickBox.IO | JMSolo
# URL:      https://plaza.quickbox.io
#
# QuickBox Copyright (C) 2016 Swizards.net
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
OUTTO=/srv/rutorrent/home/db/output.log

function _installplugin-rpc() {
  username=$(whoami);
  rutorrent="/srv/rutorrent/";
  echo "Accessing rpc in the plugin vault ... " >>"${OUTTO}" 2>&1;
  PLUGINVAULT="/root/quickbox_rutorrent-plugins/"; cd "${rutorrent}plugins"
  sleep 5

  echo "Installing rpc plugin ... " >>"${OUTTO}" 2>&1;
  PLUGIN="rpc"
    for i in $PLUGIN; do
      cp -R "${PLUGINVAULT}$i" .
    done
  sleep 5

  echo "Adjusting permissions ... " >>"${OUTTO}" 2>&1;
  chown -R www-data: ${rutorrent}plugins/$PLUGIN
  echo "RPC Plugin Install Complete!" >>"${OUTTO}" 2>&1;
  sleep 5

  echo "Refreshing your browser in 5 seconds" >>"${OUTTO}" 2>&1;
  sleep 5

  printf "" > /srv/rutorrent/home/db/output.log
  exit
}

_installplugin-rpc
