#!/bin/bash
#
# [Quick Box :: Install Plex Request.NET package]
#
# GITHUB REPOS
# GitHub _ packages  :   https://github.com/QuickBox/quickbox_packages
# LOCAL REPOS
# Local _ packages   :   ~/QuickBox/packages
# Author             :   QuickBox.IO | liara
# URL                :   https://plaza.quickbox.io
#
# QuickBox Copyright (C) 2016
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#

function _depends() {
  if [[ ! -f /etc/apt/sources.list.d/mono-xamarin.list ]]; then
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF >/dev/null 2>&1
    echo "deb http://download.mono-project.com/repo/debian wheezy main" > /etc/apt/sources.list.d/mono-xamarin.list >/dev/null 2>&1
    echo "deb http://download.mono-project.com/repo/debian wheezy-libjpeg62-compat main" >> /etc/apt/sources.list.d/mono-xamarin.list >/dev/null 2>&1
    echo "deb http://download.mono-project.com/repo/debian wheezy-apache24-compat main" >> /etc/apt/sources.list.d/mono-xamarin.list >/dev/null 2>&1
  fi

  apt-get update -q >/dev/null 2>&1
  apt-get install -q -y mono-devel mono-complete unzip >/dev/null 2>&1
}

function _install() {
  cd /opt
  curl -sL https://git.io/vKEJz | grep release | grep zip | cut -d "\"" -f 2 | sed -e 's/\/tidusjar/https:\/\/github.com\/tidusjar/g' | xargs wget --quiet -O PlexRequests.zip >/dev/null 2>&1
  unzip PlexRequests.zip >/dev/null 2>&1
  mv Release plexrequests
  chown -R ${user}: plexrequests
}


function _services() {
  cp ${local_setup}templates/sysd/plexrequests.template /etc/systemd/system/plexrequests.service
  sed -i "s/USER/${user}/g" /etc/systemd/system/plexrequests.service
  systemctl enable plexrequests >/dev/null 2>&1
  systemctl start plexrequests
  touch /install/.plexrequests.lock
  cat > /etc/apache2/sites-enabled/plexrequests.conf <<EOF
<Location /plexrequests>
ProxyPass http://localhost:3000/plexrequests
ProxyPassReverse http://localhost:3000/plexrequests
Require all granted
</Location>
EOF
  chown www-data: /etc/apache2/sites-enabled/plexrequests.conf
  service apache2 restart
}

spinner() {
    local pid=$1
    local delay=0.25
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [${bold}${yellow}%c${normal}]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
    echo -ne "${OK}"
}

OUTTO=/srv/rutorrent/home/db/output.log
local_setup=/root/QuickBox/setup/
user=$(cat /srv/rutorrent/home/db/master.txt)

echo "Updating dependencies ... " > ${OUTTO} 2>&1
echo -en "\rUpdating dependencies ... ";_depends
echo "Installing Plex Requests ... " >> ${OUTTO} 2>&1
echo -en "\rInstalling Plex Requests ... ";_install
echo "Initializing Plex Request service ... " >> ${OUTTO} 2>&1
echo -en "\rInitializing Plex Request service ... ";_services
echo "Plex Requests Installation Complete!" >> ${OUTTO} 2>&1
echo -en "\rPlex Requests Installation Complete!"
  sleep 5
echo >>"${OUTTO}" 2>&1;
echo >>"${OUTTO}" 2>&1;
echo "Close this dialog box to refresh your browser" >>"${OUTTO}" 2>&1;

echo ""
