#!/bin/bash
#
# [Quick Box :: Install Quassel IRC Bouncer package]
#
# GitHub:   https://github.com/QuickBox/quickbox_packages
# Author:   QuickBox.IO | liara
# URL:      https://plaza.quickbox.io
#
# QuickBox Copyright (C) 2016
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################

OUTTO=/srv/rutorrent/home/db/output.log
distribution=$(lsb_release -is)
IP=$(ip route get 8.8.8.8 | awk 'NR==1 {print $NF}')


function _installQuassel1() {
if [[ $distribution == Ubuntu ]]; then
	apt-add-repository ppa:mamarley/quassel -y >/dev/null 2>&1
	apt-get -qq -y --force-yes update >/dev/null 2>&1
  apt-get -q -y install quassel-core >/dev/null 2>&1
  touch /install/.quassel.lock
else
  wget -r -l1 --no-parent -O quassel-core.deb -A "quassel-core*.deb" https://iskrembilen.com/quassel-packages-debian/ >/dev/null 2>&1
  dpkg -i quassel-core* >/dev/null 2>&1
  rm quassel-core*
  apt install -f -y -q >/dev/null 2>&1
  touch /install/.quassel.lock
fi
}


function _installQuassel2() {
  exit
}



echo "Installing Quassel PPA (Ubuntu) or grabbing latest backport (Debian) ... " >>"${OUTTO}" 2>&1;_installQuassel1
echo "Quassel has now been installed! Please install quassel-client on your personal computer and connect to the newly created core at ${IP}:4242 to set up your account" >>"${OUTTO}" 2>&1;_installQuassel2
