#!/bin/bash
#
# [Quick Box :: Install Let's Encrypt package]
#
# GITHUB REPOS
# GitHub _ packages  :   https://github.com/QuickBox/quickbox_packages
# LOCAL REPOS
# Local _ packages   :   ~/QuickBox/packages
# Author             :   Neilpang | adaptive build QuickBox.IO
# URL                :   https://plaza.quickbox.io
#
# QuickBox Copyright (C) 2016 QuickBox.io
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.

service apache2 stop

cd /root
mkdir -p /etc/apache2/ssl/{site,certs}
git clone https://github.com/Neilpang/acme.sh.git acme.sh-master
cd /root/acme.sh-master

echo -ne "Please enter an administrator email: " ; read EMAIL
echo -ne "Please enter a valid domain: " ; read DOMAIN

./acme.sh --install --accountconf /etc/apache2/ssl/site/$DOMAIN.conf --accountkey /etc/apache2/ssl/site/$DOMAIN.key --accountemail "$EMAIL"
./acme.sh --issue --standalone --keypath /etc/apache2/ssl/certs/$DOMAIN-ssl.key --fullchainpath /etc/apache2/ssl/certs/$DOMAIN-ssl.pem -d $DOMAIN

cat > /etc/apache2/sites-enabled/$DOMAIN-ssl.conf <<EOF
<VirtualHost *:443>
Options +Indexes +MultiViews +FollowSymLinks
SSLEngine on
        DocumentRoot "/srv/rutorrent/home"
        <Directory "/srv/rutorrent/home/">
                Options +Indexes +FollowSymLinks +MultiViews
                AllowOverride All AuthConfig
                Order allow,deny
                Allow from all
        AuthType Digest
        AuthName "REALM"
        AuthUserFile 'HTPASSWD'
        Require valid-user
        </Directory>
        SSLEngine on
        SSLProtocol all -SSLv2
        SSLCipherSuite ALL:!ADH:!EXPORT:!SSLv2:RC4+RSA:+HIGH:+MEDIUM:+LOW
        SSLCertificateFile /etc/apache2/ssl/certs/$DOMAIN-ssl.pem
        SSLCertificateKeyFile /etc/apache2/ssl/certs/$DOMAIN-ssl.key
        SetEnvIf User-Agent ".*MSIE.*" \
                 nokeepalive ssl-unclean-shutdown \
                 downgrade-1.0 force-response-1.0
</Virtualhost>
EOF

service apache2 restart
