#!/bin/bash
#
# [Quick Box :: Install systemd services]
#
# GitHub:   https://github.com/QuickBox/quickbox_packages
# Author:   QuickBox.IO | liara
# URL:      https://plaza.quickbox.io
#
# QuickBox Copyright (C) 2016 Swizards.net
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#

function _removecron() {
for i in "${users[@]}"; do
  sudo -u ${i} crontab -l | sed '/.startup/d' | crontab -
done
rm /install/.cron.lock
}

function _installd() {
locks=($(find ${local_setup}templates/system -type f -printf "%f\n" | cut -d "." -f 1 ))
for i in "${locks[@]}"; do
  if [[ -f /install/.$i.lock ]]; then
    arr=$($arr $i)
    pkill $i
    cp ${local_setup}templates/system/$i.template /etc/systemd/system/$i@.service
    if [[ $i == autodl-irssi ]]; then
    mv /etc/systemd/system/autodl-irssi@.service /etc/systemd/system/irssi@.service
    fi
  fi
done
 for i in "${arr[@]}"; do
   if [[ $i == autodl-irssi ]]; then
     i=irssi
   fi
  systemctl enable $i@$master
  systemctl start $i@$master
done
}

local_setup=/root/QuickBox/setup/
users=($(cat /etc/htpasswd | cut -d ":" -f 1))
master=($(cat /srv/rutorrent/home/db/master.txt))
_removecron
_installd
