#!/bin/bash
#
# [Quick Box :: Install Jackett package]
#
# GitHub:   https://github.com/QuickBox/QuickBox
# Author:   Swizards.net
# URL:      https://swizards.net
#
# QuickBox Copyright (C) 2016 Swizards.net
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.

OUTTO=/srv/rutorrent/home/db/output.log
username=$(cat /srv/rutorrent/home/db/master.txt)
local_setup=/root/QuickBox/setup/
jackettver=$(wget -q https://github.com/Jackett/Jackett/releases/latest -O - | grep -E \/tag\/ | awk -F "[><]" '{print $3}')
echo >>"${OUTTO}" 2>&1;
echo >>"${OUTTO}" 2>&1;
echo "Installing Jackett ... " >>"${OUTTO}" 2>&1;

cd /home/$username
wget -q https://github.com/Jackett/Jackett/releases/download/$jackettver/Jackett.Binaries.Mono.tar.gz
tar -xvzf Jackett.Binaries.Mono.tar.gz
rm Jackett.Binaries.Mono.tar.gz
chown ${username}.${username} -R Jackett
touch /install/.jackett.lock

if [[ ! -f /install/.cron.lock ]]; then
  cp ${local_setup}templates/sysd/jackett.template /etc/systemd/system/jackett@.service
  systemctl enable jackett@${username}
  systemctl start jackett@${username}
else
  cp ${local_setup}templates/sysv/jackett.template /etc/init.d/jackett
  sed -i "s/.*APP_PATH.*/APP_PATH=\/home\/${username}\/Jackett/" /etc/init.d/jackett
  sed -i "s/.*RUN_AS.*/RUN_AS=${username}/" /etc/init.d/jackett
  chmod +x /etc/init.d/jackett
  update-rc.d jackett defaults
  service jackett start
fi

echo >>"${OUTTO}" 2>&1;
echo >>"${OUTTO}" 2>&1;
echo "Jackett Install Complete!" >>"${OUTTO}" 2>&1;

echo "Close this dialog box to refresh your browser" >>"${OUTTO}" 2>&1;
