#!/bin/bash
#
# [Quick Box :: Install SickRage package]
#
# GitHub:   https://github.com/QuickBox/quickbox_packages
# Author:   QuickBox.IO | JMSolo
# URL:      https://plaza.quickbox.io
#
# QuickBox Copyright (C) 2016 Swizards.net
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
MASTER=$(cat /srv/rutorrent/home/db/master.txt)
OUTTO=/srv/rutorrent/home/db/output.log
local_setup=/root/QuickBox/setup/

function _installSickRage1() {
  sudo git clone https://github.com/SickRage/SickRage.git  /home/"${MASTER}"/.sickrage >/dev/null 2>&1
}
function _installSickRage2() {
  touch /install/.sickrage.lock
  chown "${MASTER}":"${MASTER}" -R /home/"${MASTER}"/.sickrage
}
function _installSickRage3() {
  cd /home/"${MASTER}"/.sickrage/runscripts
  cd /etc/init.d/
  cp ${local_setup}templates/sickrage.template /etc/init.d/sickrage
  sudo chmod +x /etc/init.d/sickrage

echo -e "SR_HOME=/home/${MASTER}/.sickrage/
SR_DATA=/home/${MASTER}/.sickrage/
SR_USER=${MASTER}" > /etc/default/sickrage

  update-rc.d sickrage defaults
}
function _installSickRage4() {
  sudo service sickrage start >/dev/null 2>&1
}

function _installSickRage5() {
  echo "SickRage Install Complete!" >>"${OUTTO}" 2>&1;
  sleep 5
  echo >>"${OUTTO}" 2>&1;
  echo >>"${OUTTO}" 2>&1;
  echo "Close this dialog box to refresh your browser" >>"${OUTTO}" 2>&1;
}
function _installSickRage6() {
  exit
}

echo "Installing sickrage ... " >>"${OUTTO}" 2>&1;_installSickRage1
echo "Setting up sickrage permissions ... " >>"${OUTTO}" 2>&1;_installSickRage2
echo "Setting up sickrage configurations ... " >>"${OUTTO}" 2>&1;_installSickRage3
echo "Starting sickrage ... " >>"${OUTTO}" 2>&1;_installSickRage4
_installSickRage5
_installSickRage6
