#!/bin/bash
#
# [Quick Box :: Uninstaller for Deluge package]
#
# GitHub:   https://github.com/QuickBox/quickbox_packages
# Author:   QuickBox.IO | liara
# URL:      https://plaza.quickbox.io
#
# QuickBox Copyright (C) 2016
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
username=$(cat /etc/apache2/master.txt)
OUTTO="/root/quick-box.log"
local_setup=/root/QuickBox/setup/

function _removeDeluge() {
  killall deluged
  killall deluge-web
  cp "${local_setup}"templates/startup.template /home/"${username}"/.startup
    sleep 5
  sudo rm /install/.deluge.lock

  cd /home/"$username"
  sudo rm -r .config

}

_removeDeluge
