#!/bin/bash
username=$(cat /srv/rutorrent/home/db/master.txt)

rm -r /home/$username/Jackett
rm /install/.jackett.lock
if [[ ! -f /install/.cron.lock ]]; then
  systemctl stop jackett@${username}
  systemctl disable jackett@${username}
  rm /etc/systemd/system/jackett@.service
else
  rm /etc/init.d/jackett
  update-rc.d -f jackett remove
  service jackett stop
fi
