#!/bin/bash
#
# [Quick Box :: Remove subsonic package]
#
# QUICKLAB REPOS
# QuickLab _ packages  :   https://lab.quickbox.io/QuickBox/quickbox_packages
# LOCAL REPOS
# Local _ packages   :   ~/QuickBox/packages
# Author             :   QuickBox.IO | JMSolo
# URL                :   https://plaza.quickbox.io
#
# QuickBox Copyright (C) 2016 QuickBox.io
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#

systemctl disable subsonic
systemctl stop subsonic
sudo rm /etc/systemd/system/subsonic.service
if [[ -f /etc/init.d/subsonic ]]; then
  service subsonic stop
  sudo rm /etc/init.d/subsonic
  sudo rm /etc/default/subsonic
fi
sudo pkill -f subsonic
sudo rm -rf /srv/subsonic
sudo rm -rf /var/subsonic
sudo rm -rf /usr/share/subsonic
sudo rm /usr/bin/subsonic

sudo rm /install/.subsonic.lock
