#!/bin/bash
#
# [Quick Box :: QuickBox Package Manager Batch CLI Installer]
#
# GitHub  :   https://github.com/QuickBox/quickbox_packages
# Local   :   ~/QuickBox/packages
# Author  :   QuickBox.io | liara
# URL     :   https://plaza.quickbox.io
#
# QuickBox Copyright (C) 2016 Swizards.net
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################

function _intro() {
  whiptail --title "QuickBox Package Manager" --msgbox "Welcome to the QuickBox Package Manger! Using this script you can choose to install and remove the packages contained within our quickbox package repository." 10 50
}

function _function() {
  whiptail --title "QBPM" --menu "Choose an option:" 12 50 3 \
               Install "Packages" \
               Remove "Packages" 2>function
  function=$(cat function)

    if [[ $function == Install ]]; then
      _install
    elif [[ $function == Remove ]]; then
      _remove
    fi
}

function _install() {
  installa=()
  for i in btsync deluge plex quassel quota rapidleech sickrage sonarr x2go; do
    if [[ ! -f /install/.$i.lock ]]; then
      installa="${installa} $i off"
    fi
  done
	whiptail --title "Install Software" --noitem --checklist --separate-output "Make some choices:" 15 26 7 ${installa[@]} 2>results
  readarray packages < results
  for i in "${packages[@]}"; do
    echo -n "Installing $i ";
    bash /usr/local/bin/quickbox/package/install/installpackage-$i
  done
  rm results
  rm function

  _function
}

function _remove() {
removea=()
for i in btsync deluge plex quassel quota rapidleech sickrage sonarr x2go; do
  if [[ -f /install/.$i.lock ]]; then
    removea="${removea} $i off"
  fi
done
whiptail --title "Remove Software" --noitem --checklist --separate-output "Make some choices:" 15 26 7 ${removea[@]} 2>results
readarray packages < results
for i in "${packages[@]}"; do
  echo -n "Removing $i ";
  bash /usr/local/bin/quickbox/package/remove/removepackage-$i
done
rm results
rm function
_function
}

spinner() {
    local pid=$1
    local delay=0.25
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [${bold}${yellow}%c${normal}]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
    echo -ne "${OK}"
}

normal=$(tput sgr0)
yellow=$(tput setaf 3)
bold=$(tput bold)
_intro
_function
