#!/bin/bash
#
# [Quick Box :: QuickBox Package Manager Batch CLI Installer]
#
# GitHub  :   https://github.com/QuickBox/quickbox_packages
# Local   :   ~/QuickBox/packages
# Author  :   QuickBox.io | liara
# URL     :   https://plaza.quickbox.io
#
# QuickBox Copyright (C) 2016 Swizards.net
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################

function _intro() {
  whiptail --title "QuickBox Package Manager" --msgbox "Welcome to the QuickBox Package Manger! Using this script you can choose to install and remove the packages contained within our quickbox package repository." 10 50
}

function _function() {
  whiptail --title "QBPM" --menu "Choose an option:" 12 50 3 \
               Install "Packages" \
               Remove "Packages" \
               Quit "" 2>function
  function=$(cat function)

    if [[ $function == Install ]]; then
      _install
    elif [[ $function == Remove ]]; then
      _remove
    elif [[ $function == Quit ]]; then
      _exit
    fi
}

function _install() {
  installa=()
    if [[ ! -f /install/.autodl.lock ]]; then
      installa="${installa} autodl off"
    fi
    if [[ ! -f /install/.btsync.lock ]]; then
      installa="${installa} btsync off"
    fi
    if [[ ! -f /install/.deluge.lock ]]; then
      installa="${installa} deluge off"
    fi
    if [[ ! -f /install/.plex.lock ]]; then
      installa="${installa} plex off"
    fi
    if [[ ! -f /install/.quassel.lock ]]; then
      installa="${installa} quassel off"
    fi
    if [[ ! -f /install/.rapidleech.lock ]]; then
      installa="${installa} rapidleech off"
    fi
    if [[ ! -f /install/.sickrage.lock ]]; then
      installa="${installa} sickrage off"
    fi
    if [[ ! -f /install/.sonarr.lock ]]; then
      installa="${installa} sonarr off"
    fi
    if [[ ! -f /install/.x2go.lock ]]; then
      installa="${installa} x2go off"
    fi
	whiptail --title "Install Software" --noitem --checklist --separate-output "Make some choices:" 15 26 7 ${installa[@]} 2>results


	while read choices; do
        case $choices in
          autodl) echo -n "Installing Autodl ... ";_installautodl & spinner $!;echo
          ;;
					btsync) echo -n "Installing Btsync ... ";_installbtsync & spinner $!;echo
					;;
					deluge) echo -n "Installing Deluge ... ";_installdeluge & spinner $!;echo
					;;
          plex) echo -n "Installing Plex ... ";_installplex & spinner $!;echo
          ;;
					quassel) echo -n "Installing Quassel-Core ... ";_installquassel & spinner $!;echo
					;;
					rapidleech) echo -n "Installing Rapidleech ... ";_installrapidleech & spinner $!;echo
					;;
					sickrage) echo -n "Installing SickRage ... ";_installsickrage & spinner $!;echo
					;;
					sonarr) echo -n "Installing Sonarr ... ";_installsonarr & spinner $!;echo
					;;
					x2go) echo -n "Installing x2Go ... ";_installx2go & spinner $!;echo
					;;
          *)
          ;;

		esac
	done < results
  _function
}

function _remove() {
removea=()
  if [[ -f /install/.autodl.lock ]]; then
    removea="${removea} autodl off"
  fi
  if [[ -f /install/.btsync.lock ]]; then
    removea="${removea} btsync off"
  fi
  if [[ -f /install/.deluge.lock ]]; then
    removea="${removea} deluge off"
  fi
  if [[ -f /install/.plex.lock ]]; then
    removea="${removea} plex off"
  fi
  if [[ -f /install/.quassel.lock ]]; then
    removea="${removea} quassel off"
  fi
  if [[ -f /install/.rapidleech.lock ]]; then
    removea="${removea} rapidleech off"
  fi
  if [[ -f /install/.sickrage.lock ]]; then
    removea="${removea} sickrage off"
  fi
  if [[ -f /install/.sonarr.lock ]]; then
    removea="${removea} sonarr off"
  fi
  if [[ -f /install/.x2go.lock ]]; then
    removea="${removea} x2go off"
  fi
whiptail --title "Install Software" --noitem --checklist --separate-output "Make some choices:" 15 26 7 ${removea[@]} 2>results



  while read choices; do
        case $choices in
          autodl) echo -n "Removing Autodl ... ";_removeautodl & spinner $!;echo
          ;;
          btsync) echo -n "Removing Btsync ... ";_removebtsync & spinner $!;echo
          ;;
          deluge) echo -n "Removing Deluge ... ";_removedeluge & spinner $!;echo
          ;;
          plex) echo -n "Removing Plex ... ";_removeplex & spinner $!;echo
          ;;
          quassel) echo -n "Removing Quassel-Core ... ";_removequassel & spinner $!;echo
          ;;
          rapidleech) echo -n "Removing Rapidleech ... ";_removerapidleech & spinner $!;echo
          ;;
          sickrage) echo -n "Removing SickRage ... ";_removesickrage & spinner $!;echo
          ;;
          sonarr) echo -n "Removing Sonarr ... ";_removesonarr & spinner $!;echo
          ;;
          x2go) echo -n "Removing x2Go ... ";_removex2go & spinner $!;echo
          ;;
          *)
          ;;
    esac
  done < results
  _function
}

function _installautodl() {
  if [[ ! -f /install/.autodl.lock ]]; then
    bash /usr/local/bin/quickbox/package/install/installpackage-autodl
  else
    echo -n "Autodl already installed! Skipping ... "
fi
}

function _installbtsync() {
if [[ ! -f /install/.btsync.lock ]]; then
  bash /usr/local/bin/quickbox/package/install/installpackage-btsync
else
  echo -n "Btsync already installed! Skipping ... "
fi
}

function _installdeluge() {
if [[ ! -f /install/.deluge.lock ]]; then
  bash /usr/local/bin/quickbox/package/install/installpackage-deluge
else
  echo -n "Deluge already installed! Skipping ... "
fi
}

function _installplex() {
if [[ ! -f /install/.plex.lock ]]; then
  bash /usr/local/bin/quickbox/package/install/installpackage-plex
else
  echo -n "Plex already installed! Skipping ... "
fi
}

function _installquassel() {
if [[ ! -f /install/.quassel.lock ]]; then
  bash /usr/local/bin/quickbox/package/install/installpackage-quassel
else
  echo -n "Quassel already installed! Skipping ... "
fi
}

function _installrapidleech() {
if [[ ! -f /install/.rapidleech.lock ]]; then
  bash /usr/local/bin/quickbox/package/install/installpackage-rapidleech
else
  echo -n "Rapidleech already installed! Skipping ... "
fi
}

function _installsickrage() {
if [[ ! -f /install/.sickrage.lock ]]; then
  bash /usr/local/bin/quickbox/package/install/installpackage-sickrage
else
  echo -n "Sickrage already installed! Skipping ... "
fi
}

function _installsonarr() {
if [[ ! -f /install/.sonarr.lock ]]; then
  bash /usr/local/bin/quickbox/package/install/installpackage-sonarr
else
  echo -n "Sonarr already installed! Skipping ... "
fi
}

function _installx2go() {
if [[ ! -f /install/.x2go.lock ]]; then
  bash /usr/local/bin/quickbox/package/install/installpackage-x2go
else
  echo -n "x2go already installed! Skipping ... "
fi
}

function _removeautodl() {
if [[ -f /install/.autodl.lock ]]; then
  bash /usr/local/bin/quickbox/package/remove/removepackage-autodl
else
  echo -n "Autodl not installed. Not removing ... "
fi
}

function _removebtsync() {
if [[ -f /install/.btsync.lock ]]; then
  bash /usr/local/bin/quickbox/package/remove/removepackage-btsync
else
  echo -n "Btsync not installed. Not removing ... "
fi
}

function _removedeluge() {
if [[ -f /install/.deluge.lock ]]; then
  bash /usr/local/bin/quickbox/package/remove/removepackage-deluge
else
  echo -n "Deluge not installed. Not removing ... "
fi
}

function _removeplex() {
if [[ -f /install/.plex.lock ]]; then
  bash /usr/local/bin/quickbox/package/remove/removepackage-plex
else
  echo -n "Plex not installed. Not removing ... "
fi
}

function _removequassel() {
if [[ -f /install/.quassel.lock ]]; then
  bash /usr/local/bin/quickbox/package/remove/removepackage-quassel
else
  echo -n "Quassel not installed. Not removing ... "
fi
}

function _removerapidleech() {
if [[ -f /install/.rapidleech.lock ]]; then
  bash /usr/local/bin/quickbox/package/remove/removepackage-rapidleech
else
  echo -n "Rapidleech not installed. Not removing ... "
fi
}

function _removesickrage() {
if [[ -f /install/.sickrage.lock ]]; then
  bash /usr/local/bin/quickbox/package/remove/removepackage-sickrage
else
  echo -n "Sickrage not installed. Not removing ... "
fi
}

function _removesonarr() {
if [[ -f /install/.sonarr.lock ]]; then
  bash /usr/local/bin/quickbox/package/remove/removepackage-sonarr
else
  echo -n "Sonarr not installed. Not removing ... "
fi
}

function _removex2go() {
if [[ -f /install/.x2go.lock ]]; then
  bash /usr/local/bin/quickbox/package/remove/removepackage-x2go
else
  echo -n "x2go not installed. Not removing ... "
fi
}

function _exit() {
  printf "Goodbye!"
  printf ""
  rm function
  rm results
  exit
}

spinner() {
    local pid=$1
    local delay=0.25
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [${bold}${yellow}%c${normal}]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
    echo -ne "${OK}"
}

normal=$(tput sgr0)
yellow=$(tput setaf 3)
bold=$(tput bold)
_intro
_function
