#!/bin/bash
#
# [Quick Box Reload script]
#
# GitHub:   https://github.com/Swizards/QuickBox
# Author:   QuickBox | Swizards
# URL:      https://plaza.quickbox.io/
#
OUTTO=/dev/null
export USER=$(id -un)
pkill -u $USER irssi >/dev/null 2>&1
pkill -u $USER rtorrent >/dev/null 2>&1
killall -u $USER main >/dev/null 2>&1
rm -rf ~/.sessions/rtorrent.lock
